### ISSUE TITLE
should this work with react-native?

### ISSUE THREAD

**Issue by grubstarstar** [memoize-immutable/memoize-immutable#4]

**Comment by louisremi** [comment]
Hi there!

This module can be used in environments that natively support Map and WeakMap. I've never tried react-native so I'm not sure the environment implements it natively. Please give it a try and let me know!

**Comment by cooperka** [comment]
I can verify this library works for me using React Native v0.44.

The only caveat is that the RN Packager tries to consume the published `.babelrc`, but rather than adding a PR to every library under the sun to ignore that file, there's an easy workaround: https://github.com/facebook/react-native/issues/4062#issuecomment-164598155

```
"postinstall": "find node_modules -type f -name .babelrc | grep -v /react-native/ | xargs rm"
```

**Comment by louisremi** [comment]
Thanks again, I'm closing the issue.
